// WARNING: DO NOT EDIT THIS FILE. THIS FILE IS MANAGED BY SPRING ROO.
// You may push code into the target .java compilation unit if you wish to edit any member(s).

package system.engineer.hotel.domain;

import org.springframework.beans.factory.annotation.Configurable;
import system.engineer.hotel.domain.Room;

privileged aspect Room_Roo_Configurable {
    
    declare @type: Room: @Configurable;
    
}
